const students = [

    {
        roll        : 1,
        name        : 'Md Saikat',
        age         : 15, 
        location    : 'JIbonpur',
        gender      : 'Male',
        bn          : 87,
        en          : 90, 
        math        : 78,
        s           : 87, 
        ss          : 23, 
        rel         : 95,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbKtsJDFh8WVqq0deNDCMbzh02mtq7vH04Ng&usqp=CAU`
    },
    {
        roll        : 2,
        name        : 'Md Srabon',
        age         : 14, 
        location    : 'Majhina',
        gender      : 'Male',
        bn          : 67,
        en          : 40, 
        math        : 78,
        s           : 87, 
        ss          : 90, 
        rel         : 80,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTacNUMyMgxdYf7lnm-ysInSJg7RFeB6o7BxIzr59rOZecFrGR1QClvNI3Pim42LIldh1c&usqp=CAU`
    },
    {
        roll        : 3,
        name        : 'Md Sifat',
        age         : 15, 
        location    : 'Angra',
        gender      : 'Male',
        bn          : 20,
        en          : 90, 
        math        : 78,
        s           : 87, 
        ss          : 23, 
        rel         : 40,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEAg73lyPAdTFYB8PwG_PTT2dpvg8pk65nOA&usqp=CAU`
    },
    {
        roll        : 4,
        name        : 'Md Ismail',
        age         : 17, 
        location    : 'Jibonpur',
        gender      : 'Male',
        bn          : 67,
        en          : 90, 
        math        : 78,
        s           : 87, 
        ss          : 95, 
        rel         : 80,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuZZneDd4anaHRUJzjljdr9qGCRof1WFnNjQ&usqp=CAU`
    },
    {
        roll        : 5,
        name        : 'Md Sabbir',
        age         : 16, 
        location    : 'Jibonpur',
        gender      : 'Male',
        bn          : 67,
        en          : 40, 
        math        : 28,
        s           : 87, 
        ss          : 90, 
        rel         : 80,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9gp-_ECxjxKvd9UosODbT3mw2JV9_M_2Qwg&usqp=CAU`
    },
    {
        roll        : 6,
        name        : 'Md Setu',
        age         : 15, 
        location    : 'Uttara',
        gender      : 'Male',
        bn          : 20,
        en          : 90, 
        math        : 78,
        s           : 37, 
        ss          : 23, 
        rel         : 80,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzKBdxj4Obd4XBlUOpT7haeV6x7INZbMLPWw&usqp=CAU`
    },
    {
        roll        : 7,
        name        : 'Md Sadakatul',
        age         : 16, 
        location    : 'Majhina',
        gender      : 'Male',
        bn          : 67,
        en          : 50, 
        math        : 78,
        s           : 87, 
        ss          : 23, 
        rel         : 80,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZM2Bo80MNui7O5IsxgYBvr25QnvrRNHL9sA&usqp=CAU`
    },
    {
        roll        : 8,
        name        : 'Md Naimul',
        age         : 14, 
        location    : 'Angra',
        gender      : 'Male',
        bn          : 67,
        en          : 40, 
        math        : 78,
        s           : 87, 
        ss          : 90, 
        rel         : 90,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM-31eNbthR2DmKQ8WEk_9oOd_BPrRFfZKeA&usqp=CAU`
    },
    {
        roll        : 9,
        name        : 'Ms. Munni',
        age         : 13, 
        location    : 'Jibonpur',
        gender      : 'Female',
        bn          : 20,
        en          : 90, 
        math        : 78,
        s           : 87, 
        ss          : 23, 
        rel         : 80,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7gRzj_8KKXfCYDSGRDiOj4uAEgj7bWVPT5g&usqp=CAU`
    },
    {
        roll        : 9,
        name        : 'Ms. Ranu',
        age         : 14, 
        location    : 'Majhina',
        gender      : 'Female',
        bn          : 80,
        en          : 90, 
        math        : 78,
        s           : 87, 
        ss          : 33, 
        rel         : 80,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0qdR75o88kuYWDiL8vNqR_pmo33eay6W2Tg&usqp=CAU`
    },
    {
        roll        : 9,
        name        : 'Ms. Ayesha',
        age         : 18, 
        location    : 'Angra',
        gender      : 'Female',
        bn          : 40,
        en          : 90, 
        math        : 78,
        s           : 87, 
        ss          : 53, 
        rel         : 80,
        image       : `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8lbWhDZt71zSftOtZRqFRJQ5lmUo99igmEA&usqp=CAU`
    }

];